# Left section: current mode
# Keep spacing tight so the tab style looks continuous.
set -g status-left-length 100
set -g status-left "#{?client_prefix,#[fg=white] Tmux ,#[fg=green] Normal }#[default]"

# Window tabs
setw -g window-status-separator ""
setw -g window-status-format "#[fg=green]#[fg=black,bg=green] #W #[fg=green,bg=default]"
setw -g window-status-current-format "#[fg=yellow]#[fg=black,bg=yellow] #W #[fg=yellow,bg=default]"

# Right section: user and clock
set -g status-right-length 150
set -g status-right "#[fg=blue] #[fg=blue,bold,italic]#(whoami | tr '[:lower:]' '[:upper:]') #[fg=red]#[fg=black,bg=red] 󱑎 %H:%M  󰸗 %a,%d/%m/%y #[fg=red,bg=default]"